version: v2beta1

localRegistry:
   enabled: false

vars:
    ENV_NAME: "dev"
    ENV_SUFFIX_NAME: ""
    INGRESS_PREFIX: redact-ui
    SERVICE_NAME: ${ENTITY_NAME}
    SUFFIXED_ENTITY_NAME: ${ENTITY_NAME}${ENV_SUFFIX_NAME}
    DEVSPACE_FLAGS: 
        value: "-n ${NAMESPACE_NAME}"
    GCP_PROJECT:  "dev-gogatewayai-458208"
    NAMESPACE_NAME: "gatewayai"
    REGISTRY: us-central1-docker.pkg.dev
    REGISTRY_PULL: us-central1-docker.pkg.dev
    REGISTRY_REPO: ${GCP_PROJECT}/gogatewayai-dev-container-registry
    REQUIRE_PULL_SECRET: false 
    SERVICE_PORT: 3000
    KANIKO_SA: ksa-gateway-build

    MAIN_VALUES_FILE: $GITOPS_REPO_PATH/$GITOPS_FOLDER_PATH/$ENTITY_NAME/values.yaml 
    DEV_ENVIRON_VALUES_FILE: $GITOPS_REPO_PATH/$GITOPS_FOLDER_PATH/$ENTITY_NAME/dev/values.yaml

# This is a list of `pipelines` that DevSpace can execute
pipelines:
  dev:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      start_dev app
  build: 
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images app
  deploy:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images app
      # Add deployment logic here if needed

images:
    app:
        image: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}
        tags:
            - '#####'
            - latest
        dockerfile: "./Dockerfile.gcp"
        context: .

dev:
  app:
    imageSelector: ${REGISTRY_PULL}/${REGISTRY_REPO}/${ENTITY_NAME}
    devImage: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}:latest
    sync:
      - path: ./
        printLogs: true
        excludePaths:
          - node_modules/
          - .git
          - .env
        onUpload:
          restartContainer: true
        disableDownload: true
    terminal:
      command: ./devspace_start.sh
      disableScreen: true
    logs:
      enabled: true
    ssh:
      enabled: true
    command: ["sleep"]
    args: ["infinity"]
    ports:
      - port: "${SERVICE_PORT}"
    env:
      - name: VITE_BACKEND_URL
        value: "${VITE_BACKEND_URL}"
      - name: PORT
        value: "${SERVICE_PORT}"
