version: v2beta1
name: gw-redact-ui

imports:
- git: git@github.com:gogatewayai/gw-ci-cd.git
  branch: main
  subPath: /innerdev/devspace/devspace-common.yaml

vars:
    GCP_PROJECT:
        source: env
        name: GCP_PROJECT
        default: "dev-gogatewayai-458208"
    NAMESPACE_NAME: "gatewayai"
    ENTITY_NAME: gw-redact-ui
    SERVICE_NAME: ${ENTITY_NAME}
    GITOPS_ENTITY_NAME: gw-redact-ui
    ENV_NAME: "dev"
    INGRESS_PREFIX: redact-ui
    SERVICE_PORT: 3000
    # Internal Kubernetes service URL for the backend
    VITE_BACKEND_URL: http://gw-data-room-service:8000
    SUFFIXED_ENTITY_NAME: ${ENTITY_NAME}${ENV_SUFFIX_NAME}
    DEVSPACE_FLAGS:
        value: "-n ${NAMESPACE_NAME}"

    REGISTRY: us-central1-docker.pkg.dev
    REGISTRY_PULL: us-central1-docker.pkg.dev
    REGISTRY_REPO: ${GCP_PROJECT}/gogatewayai-dev-container-registry
    REQUIRE_PULL_SECRET: true

    API_ROUTES_PREFIX: "/api/${INGRESS_PREFIX}/v1"
    HOME:
        source: env
        name: HOME

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      create_deployments --all     # 3. Deploy Helm charts and manifests specfied as "deployments"
      start_dev app                # 4. Start dev mode "app" (see "dev" section)
  # You can run this pipeline via `devspace deploy` (or `devspace run-pipeline deploy`)
  build: 
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images app
  deploy:
    run: |-
      run_dependencies --all                            # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all                         # 2. Ensure pull secrets
      build_images app
      create_deployments --all                          # 4. Deploy Helm charts and manifests specfied as "deployments"

  debug:
      run: |-
          run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
          ensure_pull_secrets --all    # 2. Ensure pull secrets
          create_deployments --all 
          start_dev debug

# This is a list of `images` that DevSpace can build for this project
images:
    app:
        image: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}
        tags:
            - '#####'
            - latest
        dockerfile: "./Dockerfile"
        docker:
            useBuildKit: true
            args: []
        appendDockerfileInstructions:
            - USER root
        buildArgs: {}
        createPullSecret: true

# This is a list of `deployments` that DevSpace can create for this project
deployments:
  gw-redact-ui:
    helm:
      values:
        containers:
          - image: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}
            imagePullPolicy: Always
            command: ["npm"]
            args: ["run", "start"]
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: SERVICE_NAME
                value: ${SERVICE_NAME}
              - name: SERVER_NAME
                value: ${SERVICE_NAME}
              - name: K8S
                value: "true"
              - name: DEPLOYMENT_TYPE
                value: "prod"
              - name: ENV_NAME
                value: "${ENV_NAME}"
              - name: ENV_SUFFIX_NAME
                value: "${ENV_SUFFIX_NAME}"
              - name: API_ROUTES_PREFIX
                value: "${API_ROUTES_PREFIX}"
              - name: HTTP_PORT
                value: "3000"
              - name: GOOGLE_CLOUD_PROJECT
                value: "${GCP_PROJECT}"
              - name: HTTP_HOST
                value: "0.0.0.0"
              - name: VITE_BACKEND_URL
                value: "http://gw-data-room-service:8000"
              - name: BACKEND_URL
                value: "http://gw-data-room-service:8000"
        serviceAccountName: ksa-gw-ms
        imagePullSecrets:
          - name: gw-redact-ui-pull-secret
        rollingUpdate:
          enabled: true
          maxSurge: "100%"
          maxUnavailable: "50%"
        service:
          ports:
            - port: 3000

dev:
  app:
    imageSelector: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}
    devImage: node:22-slim
    workingDir: /app
    sync:
      - path: .:/app
        printLogs: true
        excludePaths:
          - node_modules/
          - dist/
        onUpload:
          restartContainer: true
        disableDownload: true
    patches:
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: ksa-gw-ms

    terminal:
      command: /app/devspace_start.sh
      disableScreen: true
    env:

      - name: GOOGLE_CLOUD_PROJECT
        value: "${GCP_PROJECT}"
      - name: HTTP_HOST
        value: "0.0.0.0"
      - name: HTTP_PORT
        value: "3000"
      - name: VITE_BACKEND_URL
        value: "http://gw-data-room-service:8000"
      - name: BACKEND_URL
        value: "http://gw-data-room-service:8000"
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    command: ["sleep"]
    args: ["infinity"]
    ports:
      - port: "3000"

  debug:
    imageSelector: ${REGISTRY}/${REGISTRY_REPO}/${ENTITY_NAME}
    devImage: node:22-slim
    workingDir: /app
    sync:
      - path: .:/app
        printLogs: true
        excludePaths:
          - node_modules/
          - dist/
        onUpload:
          restartContainer: true
        disableDownload: true
    patches:
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: ksa-gw-ms

    terminal:
      disableScreen: true
      command: /app/devspace_start.sh
    env:

      - name: GOOGLE_CLOUD_PROJECT
        value: "${GCP_PROJECT}"
      - name: HTTP_HOST
        value: "0.0.0.0"
      - name: HTTP_PORT
        value: "3000"
      - name: VITE_BACKEND_URL
        value: "http://gw-data-room-service:8000"
      - name: BACKEND_URL
        value: "http://gw-data-room-service:8000"
    ssh:
      enabled: true
    proxyCommands:
      - command: devspace
      - command: kubectl
      - command: helm
      - gitCredentials: true
    command: ["sleep"]
    args: ["infinity"]
    ports:
      - port: "3000"
      - port: "9229"


# Use the `commands` section to define repeatable dev workflows for this project 
commands:
  migrate-db:
    command: |-
      echo 'This is a cross-platform, shared command that can be used to codify any kind of dev task.'
      echo 'Anyone using this project can invoke it via "devspace run migrate-db"'
  revert-dev: 
    command: |-
     kubectl delete deployment ${ENTITY_NAME}-devspace -n ${NAMESPACE_NAME}
     kubectl scale deployment ${ENTITY_NAME} -n ${NAMESPACE_NAME} --replicas=1

profiles:
- name: integration
  merge:
    vars:
      GCP_PROJECT:  "integration-gogatewayai"

- name: dev
  merge:
    vars:
       GCP_PROJECT:  "dev-gogatewayai-458208"