ARG FROM_IMAGE=node:22-slim

FROM ${FROM_IMAGE} AS base

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project code
COPY . .

# Ensure start.sh is executable
RUN chmod +x ./start.sh

# Expose port 3000
EXPOSE 3000

# Use the start script
CMD ["./start.sh"]
